apiVersion: v1
kind: Service
metadata:
  name: app-django-tmp
  labels:
    app.kubernetes.io/name: app-django-tmp
    app.kubernetes.io/component: web
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
      nodePort: 30100
  selector:
    app.kubernetes.io/name: app-django-tmp
    app.kubernetes.io/component: web


#spec:
#  type: NodePort
#  selector:
#    app: webapp   # указываем метку приложения, на которые мы будем ссылаться.
#  ports:
#    - protocol: TCP

#      port: 8081           # Inside the cluster, what port does the service expose
      ## Выставьте службу на указанном порту внутри кластера.
      ## То есть служба становится видимой на этом порту и будет отправлять запросы, сделанные на этот порт, на модули, выбранные службой.

#      targetPort: 8081     # Which port do pods selected by this service expose
      # Это порт Пода, на который отправляется запрос.
      # Ваше приложение должно прослушивать сетевые запросы на этом порту, чтобы служба работала

#      nodePort: 30100      # Which port on the node is the service available through?
      # дополнительный порт, называемый nodePort, который указывает, какой порт открыть на узлах
