apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-django-tmp
  labels:
    app.kubernetes.io/name: app-django-tmp
    app.kubernetes.io/component: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: app-django-tmp
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-django-tmp # Service will look for those PODS labels
        app.kubernetes.io/component: web
    spec:
      containers:
        - name: django-temp
          image: vasili10k/django-temp
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: pg-password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: pg-user
            - name: DATABASE_URL
              value: "postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@pg:5432/postgres"
