apiVersion: v1
kind: Secret
metadata:
  name: pg-secret
type: Opaque
data:
  # echo -n "dj-k8s-app-db" | base64
  POSTGRES_USER: YWRtaW4=
  POSTGRES_PASSWORD: YWRtaW4xMjM=
  POSTGRES_DB: ZGotazhzLWFwcC1kYg==
