apiVersion: v1
kind: Service
metadata:
  name: app-django-tmp
  labels:
    app.kubernetes.io/name: app-django-tmp
    app.kubernetes.io/component: web
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: app-django-tmp
    app.kubernetes.io/component: web
