apiVersion: v1
kind: Service
metadata:
  name: app-django-tmp
  labels:
    app.kubernetes.io/name: app-django-tmp
    app.kubernetes.io/component: web
spec:
  ports:
    - port: 80                    # Inside the cluster, what port does the service expose
      targetPort: http-nginx      # Which port do pods selected by this service expose
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: app-django-tmp
    app.kubernetes.io/component: web
