name: Build Docker Container & Push to Docker Hub Registry

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_django_job:
    uses: VasiliKavaleu/k8s-django-template/blob/master/.github/workflows/test-django.yml
  build:
    runs-on: ubuntu-latest
    needs: [test_django_job]
    steps:
      - uses: actions/checkout@v3
