name: Build Docker Container & Push to Docker Hub Registry

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test_django_job:
    uses: ./.github/workflows/test-django.yml
  build:
    runs-on: ubuntu-latest
    needs: [test_django_job]
    steps:
      - uses: actions/checkout@v3
        name: Check out code
        
      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image: vasili10k/django-temp
          tags: ${SHORT_SHA}
          registry: docker.io    # name of Docker registry
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
