name: Django CI & Postgres Test

on:
  workflow_call:
  workflow_dispatch:
#  push:
#    branches: [main]
#  pull_request:
#    branches: [main]
jobs:
  django_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    env:
      POSTGRES_DB: dockerdc
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: myuser
    services:
      postgres_main:
        image: postgres:14
        env:
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
  strategy:
    max-parallel: 4
    matrix:
      python-version: [ 3.9 ]
