name: Django CI & Postgres Test    # is displayed on repos action page [optional]

on:                         # workflow triggers [required]
  workflow_call:            # means that can be called from other workflow process
  workflow_dispatch:        # means that can be called manually
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:                      # one or more jobs [required]
  django_test:
    runs-on: ${{matrix.os}}
    defaults:
      run:
        working-directory: .
    env:
      POSTGRES_DB: dockerdc
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: myuser
    services:
      postgres_main:
        image: postgres:14
        env:
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.9 ]
        os: [ubuntu-latest]
    steps:                            # steps can run commands, setup tasks OR run an action
      - uses: actions/checkout@v3     # select an action
        name: Check out code
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |                        # runs a command-line command
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          python src/manage.py test
