apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
spec:
  rules:
   - host: app-test.com   # defined in /etc/hosts for local testing
     http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: app-django-tmp
                port:
                  number: 80
